version: "3.7"

services:

  flask:
    build: ./flask
    container_name: flask
    environment:
      - APP_NAME=flask-app
      - CAMERA_STREAM_URL=rtsp://demo:demo@ipvmdemo.dyndns.org:5541/onvif-media/media.amp?profile=profile_1_h264&sessiontimeout=60&streamtype=unicast
    expose:
      - 8080

  nginx:
    build: ./nginx
    container_name: nginx
    ports:
      - "80:80"
